name: capture
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  deepar_flutter: ^0.0.5
  permission_handler: ^10.4.5
  url_launcher: ^6.1.11
  kakao_flutter_sdk: ^1.9.0
  cached_network_image: ^3.2.3
  http: ^0.13.6
  flutter_svg: ^2.0.5
  smooth_page_indicator: ^1.2.1
  flutter_screenutil: ^5.7.0
  camera: ^0.10.5+5
  provider: ^6.1.5
  flutter_keyboard_visibility: ^6.0.0
  keyboard_detection: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/kakao_login_large_wide.png
    - assets/images/home-banner-1.png
    - assets/images/home-banner-2.png
    - assets/images/home-banner-3.png
    - assets/images/ball-cap.png
    - assets/images/beani.png
    - assets/images/bucket-hat.png
    - assets/images/low-price-banner.png
    - assets/images/best-banner.png
    - assets/images/pedora.png
    - assets/images/beremo.png
    - assets/images/sun-cap.png
    - assets/images/mountain-hat.png
    - assets/images/golf-cap.png
    - assets/images/safety-hat.png
    - assets/images/newera-logo.png
    - assets/images/adidas-logo.png
    - assets/images/nike-logo.png
    - assets/images/mlb-logo.png
    - assets/images/kodak-logo.png
    - assets/images/newbalance-logo.png
    - assets/images/binteage-theme.png
    - assets/images/casual-theme.png
    - assets/images/sporty-theme.png
    - assets/images/classic-theme.png
    - assets/images/street-theme.png
    - assets/icons/all-product-icon.svg
    - assets/icons/best-icon.svg
    - assets/icons/low-price-icon.svg
    - assets/icons/search-icon.svg
    - assets/images/outdoor.png
    - assets/images/golf.png
    - assets/images/exercise.png
    - assets/images/safe.png
    - assets/effects/test.deepar
    - assets/effects/Black_Bucket_Hat_Adidas.deepar
    - assets/effects/Black_Fedora.deepar
    - assets/effects/Black_Sport_Visor_Cap.deepar
    - assets/effects/Blue_LA_Cap.deepar
    - assets/effects/Gray_Flat_Cap.deepar
    - assets/effects/Honda_Cap_Black.deepar
    - assets/effects/Lee_Black_Bucket_hat.deepar
    - assets/effects/Lee_Green_Visor_Cap.deepar
    - assets/effects/NB_Lilac_Knit_Beanie.deepar
    - assets/effects/Nike_Pink_Cap.deepar
    - assets/effects/NodeLabs_Black_Cap.deepar
    - assets/effects/Red_Baseball_Cap.deepar
    - assets/effects/Red_Safety_Helmet.deepar
    - assets/effects/Straw_Fedora_Hat.deepar
    - assets/effects/Universal_Hunting_Cap.deepar
    - assets/effects/adidas_tail_cap.deepar
    - assets/effects/BlueLogo_Relex_Baseball_Cap.deepar
    - assets/effects/NB_Pink_ColorPointPerformence.deepar


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
